config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'items#index'

  resources :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  def to_param
    "#{id}-item"
  end

  def image_url
    mountain = (id % 2).zero? ? "mountains" : "mountains-4"
    "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/#{mountain}.png"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :destroy]

  def index
    @items = Item.order(updated_at: :desc)
    @item = Item.new
  end

  def show
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.js
      end
    end
  end

  def destroy
    @item.destroy

    respond_to do |format|
      if @item.destroyed?
        format.js
      end
    end
  end

  private

  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:value)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_item.html.erb
<div id="<%= item.to_param %>" class="card">
  <div class="card-image">
    <img src="<%= item.image_url %>" alt="">
  </div>
  <div class="card-header">
    <h4 class="card-title">Item number <%= item.id %></h4>
  </div>
  <div class="card-copy">
    <p><%= item.value %></p>
    <p><em>Last updated <%= time_ago_in_words(item.updated_at) %> ago</em></p>
    <div class="flash-notice">
      <%= link_to "Show", item_path(item, format: :html), class: "card-link" %>
    </div>
    <div class="flash-error">
      <%= link_to "Delete item", item, class: "right", data: { disable_with: "Deleting...", remote: true, method: :delete }%>
    </div>
  </div>
</div>

app/views/items/create.js.erb
document.getElementById('items').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render @item) %>');
document.getElementById('no-items').style.display = 'none';
document.getElementById('item-value').value = '';

app/views/items/destroy.js.erb
// Return to the main page when deleting on the 'show' page
if(!document.getElementById('items')) {
  Turbolinks.visit("<%= items_path %>");
}
else {
  document.getElementById('<%= @item.to_param %>').outerHTML = '';

  // Show the default view when no items are remaining
  if(!document.querySelectorAll('.card').length) {
    document.getElementById('no-items').style.display = 'block';
  }
}

app/views/items/index.html.erb
<hr>

<%= form_with(model: @item) do |f| %>
  <%= f.label :value %>
  <%= f.text_field :value, id: 'item-value' %>
  <%= f.submit data: { disable_with: "Creating..." } %>
<% end %>

<hr>

<div id="items" class="cards">
  <% @items.each do |item| %>
    <%= render item %>
  <% end %>
  <div id="no-items" style="<%= "display:none;" if @items.any? %>">
    <h2>Welcome!</h2>
    <p>Get started by creating an item.</p>
  </div>
</div>

app/views/items/show.html.erb
<%= render @item %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurbolinkToy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width">
  </head>

  <body>
    <div>
      <h1><%= link_to "Items", items_path %></h1>
      <%= yield %>
    </div>
  </body>
</html>